### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [siddharth2010/Bubbles#2]
Hi @siddharth2010  I am a logo designer and would like to contribute to your project by designing a logo for it. If you are interested, I will begin asap. Thanks and Regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by siddharth2010** [comment]
Hi @Tobaloidee! That would be amazing!! I would love that!! Thanks a ton!

**Comment by Tobaloidee** [comment]
Hi @siddharth2010  here's what I came up with...2 versions for you to choose from. I hope you like it!

![bubbles-01](https://user-images.githubusercontent.com/36028424/61194497-5b917080-a6f4-11e9-815d-6c15def44b31.png)

**Comment by siddharth2010** [comment]
@Tobaloidee , This is amazing!! Awesome job!
I really like both designs! I think the second one is just perfect for this!!

I will integrate the logos in a few days! Thanks again!!

**Comment by Tobaloidee** [comment]
will finalize the files and make a PR sir!

**Comment by Tobaloidee** [comment]
here's the PR #3 for the logo upload & readme update @siddharth2010 

you can also download the different versions and formats of your new logo [HERE](https://drive.google.com/drive/u/1/folders/1WHr2gqpPS5J4Du_HUmqZudmOs5uTIHwA)

Thanks for accepting my contribution! Till next time. - Tobaloidee

**Comment by siddharth2010** [comment]
Fixed with #3 .

**Comment by siddharth2010** [comment]
@Tobaloidee , Thanks again for the awesome logo!

I was just wondering if you could please have a look at [this](https://github.com/siddharth2010/AndroCI) repo.

Actually I am trying to make a logo for this as well, and I think you would be the best person to ask for help! Please look into it in case you get time!

**Comment by Tobaloidee** [comment]
I will for sure! :)
